### ISSUE TITLE
Update to v1.4.17

### ISSUE THREAD

**Issue by lhovo** [nippynetworks/qfirehose#1]
Please update the repo with this newer copy of QFirehose v1.4.17 
https://cnquectel-my.sharepoint.com/:u:/g/personal/america-fae_quectel_com/EaTGPLnu1LxFlOFVfLm-zGoBy5BkJG9XU9UouDGAlwQ3Gw?e=PQQgJm

https://forums.quectel.com/t/how-to-upgrade-module-thru-linux-qfirehose/15556/17

**Comment by ewildgoose** [comment]
Done. Thanks for the suggestion
