### ISSUE TITLE
Cannot build with CMake.

### ISSUE THREAD

**Issue by Nemirtingas** [nippynetworks/qfirehose#3]
https://github.com/nippynetworks/qfirehose/blob/a0514c80583474805bfabf19388c9cf3990b7589/CMakeLists.txt#L7

```
CMake Error at CMakeLists.txt:10 (add_executable):
  Cannot find source file:

    sahara_protocol.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:10 (add_executable):
  No SOURCES given to target: QFirehose
```

I believe the source list should match the unix makefile?

`firehose_protocol.c  qfirehose.c  sahara.c usb_linux.c stream_download_protocol.c md5.c usb2tcp.c`

**Comment by ewildgoose** [comment]
I'm not a Cmake user, but I pushed your suggested change. Let me know if works for you?

**Comment by Nemirtingas** [comment]
Removing this file makes the whole binary unusable, you should put the whole file list, with sahara.c in place of sahara_protocol.c

Simply like this ↓

**Comment by ewildgoose** [comment]
How about now?

**Comment by Nemirtingas** [comment]
Looks fine
